//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDocLibraryTemplate
    {
        public System.Guid docID { get; set; }
        public Nullable<System.Guid> docPassword { get; set; }
        public string docName { get; set; }
        public string docDescription { get; set; }
        public string docCategory { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<short> docPageCount { get; set; }
        public Nullable<decimal> docWidth { get; set; }
        public Nullable<decimal> docHeight { get; set; }
        public Nullable<decimal> docBleed { get; set; }
        public Nullable<byte> clientType { get; set; }
        public Nullable<short> userID { get; set; }
        public Nullable<byte> fullScreenWindow { get; set; }
        public Nullable<byte> instanceId { get; set; }
    }
}
